local K={}
K.version=dofile("/System/kernel/version.lua")
K.log=dofile("/System/kernel/log.lua")
K.signals=dofile("/System/kernel/signals.lua")
K.capabilities=dofile("/System/kernel/capabilities.lua")
K.process=dofile("/System/kernel/process.lua")
K.users=dofile("/System/kernel/users.lua")
K.ipc=dofile("/System/kernel/ipc.lua")
K.pty=dofile("/System/kernel/pty.lua")
K.device=dofile("/System/kernel/device.lua")
K.vfs=dofile("/System/kernel/vfs.lua")
K.runtime=dofile("/System/kernel/runtime.lua")
K.panic=dofile("/System/kernel/panic.lua")
K.exec=dofile("/System/kernel/exec.lua")
K.device.scan()
K.vfs.mount("/",dofile("/System/kernel/persistfs.lua").new("/"))
K.vfs.mount("/proc",dofile("/System/kernel/procfs.lua").new(K))
K.vfs.mount("/dev",dofile("/System/kernel/devfs.lua").new(K))
K.vfs.mount("/sys",dofile("/System/kernel/sysfs.lua").new(K))
K.scheduler=dofile("/System/kernel/scheduler.lua").new(K)
K.syscalls=dofile("/System/kernel/syscall.lua").new(K)
K.services=dofile("/usr/lib/cclua/service_manager.lua").new(K)
K.log.write("info","kernel","kernel initialized",K.version)
return K
